---
name: derivatives
---

## Definition

A [Derivative]{.hii} is simply another function that tells us the slope of a function

- It tells us how a function is behaving

- A [Derivative]{.hii} will be how we find the slope of our functions

. . . 

<br>

[Mathematically]{.hi}

- We will denote a [Derivative]{.hii} as $f'(x)$
    - Our original function is labeled $f(x)$ so you can read this as: "The derivative of $f(x)$ is $f'(x)$"
    - Note that $f'(x)$ is the slope of $f(x)$ at any point $x$

---

## Intuition

```{r}
library(ggplot2)
library(htmltools)

# Create time values
time <- seq(0, 10, length.out = 100)

# Calculate height values for the parabola
height <- -0.5 * (time - 5)^2 + 10

# Create a data frame
parabola_data <- data.frame(time, height)

# Create the parabola plot
parabola_plot <- ggplot(parabola_data, aes(time, height)) +
  geom_line(color = "black", size = 1) +
  theme_minimal() +
  theme(axis.text.x = element_blank(),  # Remove x-axis ticks and labels
        axis.ticks.x = element_blank(),  # Remove x-axis ticks, 
        axis.ticks.y = element_blank(),  # Remove y-axis ticks
        axis.text.y = element_blank())

parabola_plot
```

. . .

Initially, the height of the ball is [increasing]{.hi-green} over time

Eventually, the height of the ball is [decreasing]{.hi-red} over time

---

## Intuition

The sign of the derivative matters a ton!

- An [increasing derivative]{.hi-green} means that the function is [going up]{.hi-green}

- A [decreasing derivative]{.hi-red} means that the function is [going down]{.hi-red} 

. . .

The [magnitude]{.h} also carries some significance:

- A [small absolute value]{.hi} means that the [derivative is moving slowly]{.hi}

- A [large absolute value]{.hii} means that the [derivative is moving rapidly]{.hii}

. . .

> [Note: I am talking about absoltue values so this applies to both positive and negative values. Because we use negatives, our intuition may challenged a bit but hopefully a future example will clear things up]{.h .note} 

<!-- Make future example -->

---

## Derivative Equal to Zero

Functions can increase and decrease, which implies something very critical

. . .

> [Functions can have zero slope!]{.hii} This happens when the function switches from increasing to decreasing (and vice-versa)

. . .

<br>

[But Why Does This Matter?]{.h}

- The switch between positive and negative happens exactly when the function is at its maximum/minimum

- And Economics is all about maximizing stuff!

  - Sometimes we minimize a function but the logic remains the same

---

## Bringing the Math to Economics

Think about profits. 

As a firm, we want to maximize profits so we: 

:::: {.incremental}
- Write down profits as a function of quantity produced

- Take its derivative

- Set that derivative (remember it is a function) equal to zero

- Know how much quantity to produce
::::

. . .

Once we know what we are doing, the math is extremely simple. 

The hard part is understanding what we are doing, and then interpreting what a result of $x^{*} = 6$ means.

---

## How Do We Calculate Derivatives?

You may already know how to take derivatives but prepare to receive a crash-course in derivative shortcuts

. . . 

Starting with the basics:

- $y$ will be a function of $x$ such that $y = f(x)$

- I will be using variables to show general cases so you can look back at how it's done

. . .

[We will go over the following:]{.hi}

:::: {.columns}

::: {.column width="60%"}
- Power Rule

- Sum (and Difference) Rule

- Constant Rule
:::

::: {.column width="40%"}

- Log Rule

- Chain Rule
:::

::::

---

## Power Rule

This will be the most common derivative we will be using

$$y = a \cdot x^{b}$$

. . .

$$\dfrac{\delta y}{\delta x} = {\color{red}b} \cdot a \cdot x^{\color{red}{b-1}}$$

. . .

For example:

$$y = 5x^{3}$$

. . .

$$\dfrac{\delta y}{\delta x} = {\color{red}3} \cdot 5 x^{\color{red}{3-1}} = 15x^{2}$$
---

## Power Rule (Negative Exponent)

Sometimes we will see factors with a negative exponent, like $x^{-3}$ for example

As a rule of thumb, you should [always turn your negative exponents into positive ones]{.hii}

Thankfully, its a simple process:

. . .

We just "invert" the negative factor (aka flip the fraction)

$$x^{\color{red}-3} = \dfrac{1}{\color{red}{x^{3}}}$$

. . .

The derivative works exactly the same way so we can begin with the derivative and then make it positive. 

---

## Power Rule (Negative Exponent)

So for $y = 5x^{-2}$ we have:

$$\dfrac{\delta y}{\delta x} = -2 \cdot 5x^{-2-1} = -10x^{-3} = \dfrac{-10}{x^{3}}$$

I'll leave it to you to show yourself that making it $y = \dfrac{5}{x^{2}}$ gives the same result

---

## Power Rule (Fractional Exponent)

A lot of the time we will have fractional exponents (or decimals)

$$y = x^{1/5} = x^{0.2}$$

. . .

$$\dfrac{\delta y}{\delta x} = \dfrac{1}{5} \cdot x^{1/5 - 1} = \dfrac{1}{5} x^{-4/5} = \dfrac{1}{5} \cdot \dfrac{1}{x^{4/5}}$$

. . .

<br>

$$\dfrac{\delta y}{\delta x} = 0.2 \cdot x^{0.2 - 1} = 0.2 \cdot x^{-0.8} = \dfrac{0.2}{x^{0.8}}$$
---

## Power Rule (Exponent Equal to 1)

Lastly, I'll remind you that every number has a default exponent of 1

That is to say, if we see $3x$ it is equivalent to $3x^{1}$

This helps us take the derivative using the [Power Rule]{.h}

For example: $y = -3x$

. . .

$$\dfrac{\delta y}{\delta x} = 1 \cdot -3x^{1-1} = -3x^{0} = -3$$

> [The key is to remember that any number with exponent 0 equals 1]{.hi}

---

## Sum (and Difference) Rule


---

## Product Rule

---

## Constant Rule

---

## Log Rule

---

## Chain Rule

