---
name: Slope Logic
---

## Math Makes Point C special

This is the point where the BC line and the IC curve have the exact same slope, this is also known as [the point where they are tangent]{.h}

. . .

This helps us put the intuition we gained from the graph together with the math

. . .

<br> 

> [**The key to finding the utility maximizing bundle (the best mix of $x$ and $y$) you have to find the bundle where the BC and IC have the same slope**]{.h .note}

---

## Why Does This Work?

Let's recall what the [Slope of the IC]{.hi} means:

. . .

- It is the **Negative MRS** 

- It tells you how much $y$ you would be [willing to]{.hi} give up to get another unit of $x$?

. . .

Now recall what the [Slope of the BC]{.hi} means:

. . .

- It is the **Negative Price Ratio**

- It tells you how much $y$ you would [have to]{.hi} give up to get another unit of $x$?

---

## Why Does This Work?

Imagine what it would it mean if these two slopes were not equal

. . .

Let's say the [Negative MRS]{.hi} is $-4$