---
name: syllabus 
---

## Class Information

- Schedule: Days (Time) in Classroom
- Office Hours: Days (Time)
- [Attendance]{.hii} is important to your learning experience
    - A lot goes on in the class that may be hard to understand just from lecture slides

. . .

[Lectures]{.hi}
- They will be dynamic, with me asking general questions and expecting answers from you
- I will use my iPad to write on the slides and will upload the annottated slides after class
- (Maybe) Will have iClicker questions that require your presence in class

--- 

## Assignments

[Achieve Online Learning]{.hi}
{
- You [MUST]{.h} register for the course through Achieve
- This is where you will complete your homework 
- It also gives you access to the digital version of the textbook
- The course code is [code goes here]{.hp}
- Your lowest homework grade will be dropped

[Canvas Quizzes]{.hi}

- Weekly quizzes that will help you get accustomed to how test questions will look
- These are on Canvas and will be weekly 

---

## Expectations

[Prerequisites]{.hi}

- EC 201: Intro to Microeconomics
- MATH 111: 
    - MATH 241: Calculus 1 (Recommended but not required)
    - I'll give you a crashcourse in what we'll need from calculus in the next lecture

 ---

## Expectations

[What to Expect from the Course]{.hi}

- The course involves a healthy mix of math and economic theory
    - The math is relatively straightforward, but it requires a good grasp on the theory to properly interpret it 
- More importantly than committing the theory to memory, the goal is to think like an economist
    - There is a set logic in the theory that we will see and it should lead to predictable conclusions

. . .

- [I recognize that perhaps all of you are here for the requirement in your own programs, so my aim is to make it as relevant and interesting as possible]{.tiny}

- [I'm not trying to convert you into economists, but rather have you takeaway things that you can apply in your own careers]{.tiny}

--- 

## Grades

:::: {.columns}

::: {.column width="50%"}
[Homework]{.hi}

- Achieve Homework (20%)
    - [Amount of assignments here]{.hi-red}
    - [Due day]{.hi-red}
- Canvas Quizzes (15%)
    - [Amount of assignments here]{.hi-red}
    - [Due day]{.hi-red}
:::

::: {.column width=50%}
[Exams]{.hi}

- Midterm (30%)
    - [Tentatively on Week & Day]{.hi-red}
- Final (45%)
    - [Tentatively on Week & Day]{.hi-red}
:::

::::

. . . 

[Grade Notes]{.hii}
- There will most likely be a curve applied to your course grade 
- Because of this, what truly matters is the class distribution, not your raw score
    - If you are above the class average, your doing great
